language: c
env:
  - OCAML_VERSION=4.01.0
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.05.0+flambda
  - OCAML_VERSION=4.06.0
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
# Caching may take a lot of space with so many ocaml versions
#cache:
#  directories:
#    - $HOME/.opam
before_install:
  # Some opam boilerplate
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
install:
  # Install dependencies
  - opam pin add --no-action containers .
  - opam install oasis
  - opam install --deps-only containers
script:
  - ./configure --enable-unix --enable-thread --disable-tests --disable-bench
  - make build
  - opam install sequence qcheck qtest gen
  - ./configure --enable-unix --enable-thread --enable-tests --enable-docs --disable-bench
  - make test
  - make doc
